### ISSUE TITLE
Why can't it be used in ios

### ISSUE THREAD

**Issue by zgChihiro** [robinwood3d/UE4RuntimeTransformGizmo#1]
I changed all the "mouseClick" into "touch"
But I package the project to My iPad
It can't change staticMesh's Transform

**Comment by robinwood3d** [comment]
Extra works should be done if you wanna use it on other platform but PC
Due to it's only a blueprint demo, so indeed a lot of problems do exist.
Actually that's why I only keep it as a simple demo, because different projects has various demands and I may not do it all on my own. But I think the blueprints in this project is simple and good organized, it's not that hard to read.
